/* ============================================================
   JEU 3 — Données des missions du bunker
   ------------------------------------------------------------
   Chaque mission a une clé stable (pour le flag), un titre, la
   rumeur/enquête à vérifier, la liste des PNJ à interviewer
   (id, nom, rôle, réplique) et le verdict attendu.
   Verdicts possibles :
     - "rumeur"    : info fausse ou infondée
     - "fragile"   : info partiellement vérifiée
     - "solide"    : info vérifiée par plusieurs sources fiables
   ============================================================ */
export const MISSIONS_RUMEURS = {
  kova: {
    id: "kova",
    flag: "mission_kova_done",
    titre: "La rumeur du Dr Kova",
    affirmation: "Le Dr Kova aurait dit que l'air, dehors, est respirable — et que sa nièce serait sortie sans dommage.",
    /* Briefing du Juge Vez, lu au comptoir. Chaque ligne = une réplique. */
    briefing: [
      "Alors c'est toi qui a reçu le billet. Tu es le troisième cette année. Les deux autres ont abandonné.",
      "Je ne te demande pas qui tu es. On est trop d'habitants au Puits pour que je retienne les noms. Je te demande juste si tu es prêt·e à faire ce boulot.",
      "Pour commencer, un cas d'école. Un habitant, Marek, dit avoir entendu à la cantine un certain Dr Kova affirmer que sa nièce est sortie du Puits et qu'elle allait bien. Rumeur ? Vraie info ?",
      "Interroge Marek. Puis vérifie auprès de deux personnes qui pourraient savoir : l'archiviste Séra, et Yol, le garde qui veille sur la grande porte scellée. Reviens me voir avec ton verdict.",
    ],
    minWitnesses: 3,
    /* Les 3 témoins. Chacun expose une fiche + 3 questions type. Chaque
       réponse peut nourrir soit "aVu" (première main) soit "rapporte"
       (seconde main) soit "note" (contexte général). */
    temoins: [
      {
        id: "marek", nom: "Marek", role: "Habitant (retraité)",
        ancienneteAns: 12, lieu: "Cantine commune",
        pose: { x: 200, y: 400 },
        color: "#8a5030", pants: "#3a2010", hair: "#3a1808",
        facing: "right", activity: "cup",
        questions: [
          { q: "Qu'as-tu vu, de tes propres yeux ?",
            r: "Rien. De mes yeux, rien. Mais on m'a dit — et ce qu'on dit compte, non ?",
            type: "note", val: "N'a rien vu de première main." },
          { q: "Qui t'a dit ça ?",
            r: "Le Dr Kova. À la cantine, hier midi. Il parlait fort. Sa nièce serait sortie par la grande porte, l'air passait bien.",
            type: "rapporte", val: "Le Dr Kova aurait dit à voix haute que sa nièce est sortie et allait bien." },
          { q: "Depuis quand entends-tu ces bruits ?",
            r: "Une semaine. Ça a commencé ici, à la cantine, et c'est monté dans les étages.",
            type: "note", val: "La rumeur circule depuis une semaine environ." },
        ],
      },
      {
        id: "sera", nom: "Séra", role: "Archiviste",
        ancienneteAns: 8, lieu: "Salle des Archives",
        pose: { x: 500, y: 400 },
        color: "#7fd8ff", pants: "#3a4048", hair: "#5a4028",
        facing: "front", accessory: "coat", activity: "write",
        questions: [
          { q: "Un Dr Kova existe-t-il au Puits ?",
            r: "J'ai vérifié tous les registres médicaux. À aucune époque, personne du nom de Kova n'a exercé ici. Ni maintenant, ni depuis 40 ans.",
            type: "aVu", val: "A vérifié : aucun Dr Kova dans les registres médicaux depuis 40 ans." },
          { q: "Comment as-tu cherché ?",
            r: "Fichier du personnel médical, listes de logement, dossiers d'infirmerie. Trois croisements. Rien.",
            type: "note", val: "Recherche croisée sur 3 registres." },
          { q: "Une nièce, ça se pourrait ?",
            r: "Sans un Kova de référence, une « nièce de Kova » n'existe pas non plus. C'est mécaniquement impossible.",
            type: "note", val: "Sans témoin de base, pas de nièce vérifiable." },
        ],
      },
      {
        id: "yol", nom: "Yol", role: "Garde de la grande porte",
        ancienneteAns: 22, lieu: "Près de la grande porte",
        pose: { x: 800, y: 400 },
        color: "#28303a", pants: "#1a2028", hair: "#1a1408",
        facing: "front", accessory: "toolbelt", activity: "crossed",
        questions: [
          { q: "Quelqu'un est-il déjà sorti par la grande porte ?",
            r: "Personne. Depuis quarante ans. J'étais là quand on l'a soudée — c'est moi qui tenais la torche.",
            type: "aVu", val: "A soudé la grande porte il y a 40 ans. Personne n'est sorti depuis." },
          { q: "La porte pourrait-elle être forcée sans que tu le voies ?",
            r: "Non. Ça hurlerait à trois étages. Je monte la garde une nuit sur deux depuis vingt ans.",
            type: "note", val: "Poste de garde occupé une nuit sur deux depuis 20 ans." },
          { q: "As-tu déjà entendu parler d'un Dr Kova ?",
            r: "Jamais. Et j'écoute beaucoup — c'est mon métier, à la porte.",
            type: "note", val: "N'a jamais entendu le nom Kova." },
        ],
      },
    ],
    /* Les témoins qu'un enquêteur solide devrait cocher comme "fiables sur
       ce sujet" — ceux qui ont VU ou VÉRIFIÉ, pas ceux qui rapportent. */
    temoinsFiables: ["sera", "yol"],
    verdicts: [
      { id: "solide",
        label: "SOLIDE",
        desc: "L'air est respirable dehors, c'est vrai.",
        ok: false,
        retour: "Non. Un seul habitant rapporte les paroles de quelqu'un dont l'archiviste ne trouve pas la trace, et le garde dit que la porte n'a pas bougé depuis 40 ans. Solide, ce serait faire confiance au maillon le plus fragile. Recommence." },
      { id: "fragile",
        label: "FRAGILE",
        desc: "Peut-être vrai, mais on manque de preuves.",
        ok: false,
        retour: "Trop généreux. Marek n'a rien vu, il rapporte les paroles de quelqu'un qui n'existe pas dans les registres. Ce n'est pas du fragile, c'est du zéro." },
      { id: "rumeur",
        label: "RUMEUR",
        desc: "L'histoire ne tient pas.",
        ok: true,
        retour: "Verdict correct. Marek RAPPORTE — il n'a rien vu. La personne qu'il cite n'existe pas dans les registres. Le garde confirme que la porte n'a pas bougé depuis quarante ans. C'est une rumeur." },
    ],
    /* Feedback selon la précision de la sélection des témoins fiables. */
    fiablesFeedback: {
      parfait: "Et tu as coché les bons : Séra a vérifié des sources écrites, Yol a été témoin direct du soudage. Ce sont eux qui portent la preuve — pas Marek, qui ne fait que rapporter.",
      partiel: "Tu tiens un des deux témoins-clés, mais tu en manques un. Séra a VÉRIFIÉ dans des registres. Yol a VU le soudage. Ce sont eux, les témoins forts.",
      mauvais: "Attention : tu as coché quelqu'un qui rapporte. Les témoins forts sur ce sujet, ce sont Séra (registres croisés) et Yol (témoin oculaire du soudage).",
    },
    succes: "Retiens le geste : quand quelqu'un DIT que quelqu'un d'autre a DIT, remonte à la source. Si elle n'existe pas, la chaîne est rompue.",
  },

  vitamine: {
    id: "vitamine",
    flag: "mission_vitamine_done",
    prerequisite: "mission_kova_done",
    titre: "La vitamine blanche",
    affirmation: "La poudre blanche ajoutée depuis un an à nos rations, c'est une vitamine bonne pour nous.",
    briefing: [
      "Deuxième affaire. Celle-ci te plaira moins — tu la bois tous les jours.",
      "Depuis un an, une poudre blanche est mélangée dans toutes nos rations. L'étiquette dit « Vitamine M-42 ». Les habitants s'inquiètent, mais personne ne sait rien de concret.",
      "Quatre témoins ont du nouveau. Tor, aux Serres, dose cette poudre dans ses cuves. Lin, à l'infirmerie, voit arriver des patients fatigués. Bri, à la cantine, reçoit les sacs. Mel, au repos à l'infirmerie, est elle-même touchée.",
      "Je les ai convoqués ici pour que tu les entendes au comptoir. Pour la prochaine enquête, tu iras les voir sur leurs postes. Reviens avec ton verdict.",
    ],
    minWitnesses: 4,
    temoins: [
      {
        id: "tor", nom: "Tor", role: "Technicien aux Serres",
        ancienneteAns: 11, lieu: "Serres hydroponiques",
        pose: { x: 150, y: 400 },
        color: "#8a5030", pants: "#3a2010", hair: "#3a1808",
        facing: "right", accessory: "toolbelt", activity: "wrench",
        questions: [
          { q: "Que vois-tu, toi, dans tes cuves ?",
            r: "Depuis un an, cette poudre blanche arrive avec les nutriments. Je la dose moi-même. Mes tomates grossissent plus vite… mais elles n'ont plus de goût. Je peux le prouver, j'ai gardé des échantillons.",
            type: "aVu", val: "Dose la poudre lui-même. A observé que les tomates perdent leur goût depuis l'ajout." },
          { q: "On t'a dit à quoi elle sert ?",
            r: "On me dit « vitamine ». Pas de notice, pas de nom scientifique, pas d'étude. Juste un sac avec « M-42 » dessus et un planning de dosage.",
            type: "note", val: "Reçoit la poudre sans documentation scientifique." },
          { q: "D'où arrivent les sacs ?",
            r: "Du monte-charge, livrés depuis l'étage d'en dessous. Je ne vois jamais le livreur. Juste les sacs.",
            type: "rapporte", val: "Sacs livrés par monte-charge, livreur jamais vu." },
        ],
      },
      {
        id: "lin", nom: "Lin", role: "Médecin",
        ancienneteAns: 14, lieu: "Infirmerie",
        pose: { x: 420, y: 400 },
        color: "#7fd8ff", pants: "#3a4048", hair: "#5a4028",
        facing: "front", accessory: "coat", activity: "clipboard",
        questions: [
          { q: "Que soignes-tu en ce moment ?",
            r: "De plus en plus de patients viennent pour la « grande fatigue ». Trois fois plus qu'il y a un an. Je prends soin de noter chaque cas.",
            type: "aVu", val: "A noté une multiplication par 3 des cas de « grande fatigue » en un an." },
          { q: "Un lien avec la poudre ?",
            r: "Pas de preuve directe. Mais les cas montent exactement au moment où la poudre a été ajoutée aux rations. Ça peut être une coïncidence. Ça peut ne pas en être une.",
            type: "note", val: "Montée des cas corrélée à l'ajout de la poudre. Pas de preuve de causalité." },
          { q: "D'autres explications possibles ?",
            r: "Oui. L'air est confiné, on bouge peu, la population vieillit. Toutes ces explications tiennent. La coïncidence de dates me gêne quand même.",
            type: "note", val: "D'autres facteurs possibles (air, inactivité, âge)." },
        ],
      },
      {
        id: "bri", nom: "Bri", role: "Cuisinière en chef",
        ancienneteAns: 18, lieu: "Cantine commune",
        pose: { x: 720, y: 400 },
        color: "#e8dfc8", pants: "#3a2818", hair: "#8a3820",
        facing: "left", accessory: "apron", activity: "stir",
        questions: [
          { q: "Qui te livre les sacs ?",
            r: "Un porteur anonyme, par le monte-charge, tous les quinze jours. Dix kilos. Étiquette « Vitamine M-42 ». Je mélange, c'est tout.",
            type: "aVu", val: "Reçoit la poudre par livraison anonyme tous les 15 jours." },
          { q: "Tu as goûté la poudre toute seule, sans la mélanger ?",
            r: "Non. On m'a dit de ne pas y toucher telle quelle — qu'il faut toujours la diluer dans les rations. On ne m'a pas expliqué pourquoi.",
            type: "rapporte", val: "Consigne de ne pas la goûter sans mélange, sans explication." },
          { q: "Tu as posé des questions ?",
            r: "Non. Ici, on fait son travail. Si je commence à demander, je perds ma place en cuisine.",
            type: "note", val: "A choisi de ne pas poser de questions pour garder son poste." },
        ],
      },
      {
        id: "mel", nom: "Mel", role: "Patiente au repos",
        ancienneteAns: 7, lieu: "Infirmerie",
        pose: { x: 980, y: 400 },
        color: "#8a5030", pants: "#3a4048", hair: "#c8a848",
        facing: "front", activity: "cup",
        questions: [
          { q: "Pourquoi es-tu ici ?",
            r: "Grande fatigue depuis trois mois. Je dors beaucoup, je ne rêve plus. Lin m'a mise au repos.",
            type: "aVu", val: "Souffre de grande fatigue depuis 3 mois." },
          { q: "D'autres cas autour de toi ?",
            r: "Trois voisins par ce lit en un mois. Après, on les transfère à l'étage du dessus, et on ne les revoit plus. C'est bizarre.",
            type: "aVu", val: "A vu 3 voisins transférés au-dessus sans retour." },
          { q: "Un lien avec la poudre, selon toi ?",
            r: "Je ne suis pas scientifique. Mais j'ai arrêté de la prendre il y a deux semaines — j'ai triché avec les rations. Je crois sentir que je récupère.",
            type: "note", val: "A arrêté la poudre il y a 2 semaines, se sent récupérer (observation personnelle)." },
        ],
      },
    ],
    temoinsFiables: ["tor", "lin"],
    verdicts: [
      { id: "solide",
        label: "SOLIDE",
        desc: "Oui, c'est une vitamine, c'est bon pour nous.",
        ok: false,
        retour: "Trop confiant. Aucun témoin n'apporte la moindre preuve que c'est bon pour nous. Il n'y a ni notice, ni étude, ni analyse — juste une étiquette. Une étiquette toute seule, ça ne prouve rien." },
      { id: "fragile",
        label: "FRAGILE",
        desc: "On a des indices, mais pas de preuve.",
        ok: false,
        retour: "Trop neutre. Les indices ne sont pas « on ne sait pas » — ils vont tous CONTRE l'affirmation. Tor voit les tomates perdre leur goût, Lin voit la fatigue monter, Mel se sent mieux depuis qu'elle a arrêté. Zéro preuve que c'est bon, plusieurs signes que c'est l'inverse. Ça ne tient pas." },
      { id: "rumeur",
        label: "RUMEUR",
        desc: "L'affirmation « c'est bon pour nous » ne tient pas.",
        ok: true,
        retour: "Verdict juste. Trois témoins apportent des indices qui vont CONTRE l'affirmation : Tor voit les tomates perdre leur goût, Lin voit la fatigue monter en même temps que la poudre, Mel se sent mieux depuis qu'elle a arrêté. Et zéro témoin, zéro document, zéro preuve que c'est « bon pour nous ». L'affirmation ne tient pas." },
    ],
    fiablesFeedback: {
      parfait: "Et tu as repéré les bons : Tor DOSE la poudre et compare le goût, Lin COMPTE les cas de fatigue. Ils ont des mesures, pas juste des impressions. Bri et Mel apportent du contexte, mais sans mesure.",
      partiel: "Un sur deux. Les témoins forts sont ceux qui MESURENT : Tor avec ses tomates, Lin avec ses cas de fatigue. Les autres apportent du contexte utile mais sans mesure.",
      mauvais: "Attention : tu as coché quelqu'un qui apporte surtout du contexte ou une impression personnelle. Les témoins forts sont ceux qui ont des MESURES : Tor dose, Lin compte.",
    },
    succes: "Deuxième geste : quand plusieurs indices concordent et vont tous CONTRE une affirmation, cette affirmation ne tient pas. Même sans preuve absolue. On n'attend pas d'avoir TOUT prouvé pour dire que ça pue.",
  },

  jour40: {
    id: "jour40",
    flag: "mission_jour40_done",
    prerequisite: "mission_vitamine_done",
    titre: "Le quarantième jour",
    affirmation: "La coupure d'électricité qui revient toutes les 40 nuits, c'est juste une panne technique sans importance.",
    briefing: [
      "Troisième affaire. Celle-ci te chatouille parce qu'elle est régulière comme une horloge.",
      "Depuis des années, le Puits a une coupure de courant d'une minute pile toutes les 40 nuits. L'affichage officiel dit : « panne mineure, rien à signaler ». Les gens s'y sont habitués.",
      "Quatre personnes à l'atelier et aux serres ont des choses à dire là-dessus. Yon l'électricien, Gus le contremaître, Kev l'ingénieur, Flor la botaniste. Je les ai convoqués ici.",
      "Interroge-les. Vois si cette « panne mineure » tient face à leurs observations.",
    ],
    minWitnesses: 4,
    temoins: [
      {
        id: "yon", nom: "Yon", role: "Électricien",
        ancienneteAns: 16, lieu: "Atelier des Ingénieurs",
        pose: { x: 180, y: 400 },
        color: "#c8a848", pants: "#3a2818", hair: "#3a1808",
        facing: "right", accessory: "toolbelt", activity: "torch",
        questions: [
          { q: "Qu'as-tu mesuré, exactement ?",
            r: "Coupure d'une minute, à la minute pile, tous les 40 jours, à la nuit pile. J'ai tenu un relevé chronométré pendant 3 ans. Zéro écart.",
            type: "aVu", val: "Relevé chronométré sur 3 ans : coupure d'1 min, toutes les 40 nuits, à la minute pile." },
          { q: "D'où vient cette coupure ?",
            r: "D'en haut. Elle descend depuis le niveau des serveurs. Je sais lire mes câbles — c'est pas une panne qui remonte, c'est une coupure qui descend.",
            type: "aVu", val: "La coupure descend du niveau des serveurs, pas une panne électrique qui remonte." },
          { q: "Tu as alerté quelqu'un ?",
            r: "Oui. On m'a dit : « c'est noté, pas la peine d'insister ». Depuis, je ne note plus. Mais j'observe.",
            type: "note", val: "Alertes passées rejetées par la hiérarchie." },
        ],
      },
      {
        id: "gus", nom: "Gus", role: "Contremaître",
        ancienneteAns: 24, lieu: "Atelier des Ingénieurs",
        pose: { x: 450, y: 400 },
        color: "#8a5030", pants: "#3a2010", hair: "#e8dfc8", skin: "#c8a888",
        facing: "left", accessory: "coat", activity: "write",
        questions: [
          { q: "Qu'y a-t-il dans ton registre ?",
            r: "Toutes les pannes signalées depuis 8 ans. Pas une seule fois les coupures de 40 jours. Mon registre dit : « RAS » tous les 40 jours.",
            type: "aVu", val: "Registre officiel sur 8 ans : coupures des 40 jours jamais signalées — officiellement il n'y en a pas." },
          { q: "Pourquoi tu ne les signales pas ?",
            r: "Parce qu'au départ, j'ai signalé. On m'a dit : « ce n'est pas une vraie coupure, ne note rien, n'en parle pas ».",
            type: "rapporte", val: "Interdiction venue d'en haut de noter ou de parler des coupures." },
          { q: "Qui t'a dit ça ?",
            r: "L'ordre venait du planning MARTINE. Pas d'un humain. Juste une note sur mon écran : « ne pas signaler ».",
            type: "rapporte", val: "Ordre reçu directement de MARTINE, par note écran." },
        ],
      },
      {
        id: "kev", nom: "Kev", role: "Ingénieur systèmes",
        ancienneteAns: 10, lieu: "Atelier des Ingénieurs",
        pose: { x: 720, y: 400 },
        color: "#3a4048", pants: "#28303a", hair: "#2a2018",
        facing: "left", accessory: "toolbelt", activity: "wrench",
        questions: [
          { q: "Tu es déjà descendu voir MARTINE ?",
            r: "Oui, une fois, pour une maintenance en 2082. Les serveurs principaux portent une étiquette : « code modifié · 2050 ». Quelqu'un a changé ce que fait MARTINE.",
            type: "aVu", val: "Étiquette vue sur les serveurs : « code modifié · 2050 »." },
          { q: "Qu'est-ce qui a changé en 2050 ?",
            r: "Je ne sais pas précisément. Mais depuis cette date, le planning de MARTINE est verrouillé — on ne peut plus voir ce qu'elle décide, juste ce qu'elle affiche.",
            type: "note", val: "Depuis 2050, le planning MARTINE n'est plus consultable par les ingénieurs." },
          { q: "Un lien avec les 40 jours ?",
            r: "Je parierais que oui. Mais parier n'est pas prouver.",
            type: "note", val: "Soupçon de lien avec les 40 jours, non prouvé." },
        ],
      },
      {
        id: "flor", nom: "Flor", role: "Botaniste",
        ancienneteAns: 19, lieu: "Serres hydroponiques",
        pose: { x: 980, y: 400 },
        color: "#5eff9e", pants: "#3a4048", hair: "#c8a848",
        facing: "left", accessory: "coat", activity: "write",
        questions: [
          { q: "Qu'est-ce qui te fait tiquer dans ces coupures ?",
            r: "Mes plants ont besoin de 12 heures de lumière continue. La coupure de 40 jours tombe PILE pendant leur phase nuit — jamais le jour, jamais pendant leur phase lumière. Statistiquement impossible si c'était aléatoire.",
            type: "aVu", val: "Les coupures tombent toujours pendant la phase nuit des plantes, jamais le jour. Impossible si aléatoire." },
          { q: "Depuis quand remarques-tu ça ?",
            r: "J'ai croisé mon planning de lumière avec les coupures sur 5 ans. 1 500 nuits. 100 % de concordance.",
            type: "aVu", val: "5 ans de données croisées, 100 % de concordance entre coupures et phase nuit." },
          { q: "Pourquoi quelqu'un ciblerait tes plants ?",
            r: "Je l'ignore. Mais si tu veux ralentir la croissance d'une plante sans que ça se voie, tu lui coupes la lumière pendant son cycle nuit. C'est subtil. C'est efficace.",
            type: "note", val: "Hypothèse : ralentir la croissance des plants sans que ça se voie." },
        ],
      },
    ],
    temoinsFiables: ["yon", "flor"],
    verdicts: [
      { id: "solide",
        label: "SOLIDE",
        desc: "Oui, c'est une panne banale.",
        ok: false,
        retour: "Trop confiant. Trois témoins apportent des mesures précises qui vont CONTRE l'idée d'une panne banale : coupure à la minute pile, direction descendante, concordance 100 % avec les cycles des plantes. Les pannes banales ne sont pas à la minute pile." },
      { id: "fragile",
        label: "FRAGILE",
        desc: "On a des indices, mais pas de preuve.",
        ok: false,
        retour: "Trop neutre. Trois témoins apportent chacun une MESURE précise (Yon chronomètre, Gus a 8 ans de registre, Flor croise 1 500 nuits). Ensemble, ils ne sont pas « des indices » : ils sont une preuve. Il faut appeler ça par son nom." },
      { id: "rumeur",
        label: "RUMEUR",
        desc: "L'affirmation « panne banale » ne tient pas.",
        ok: true,
        retour: "Verdict juste. Trois témoins mesurent trois choses différentes et toutes les trois sortent de ce qu'on attend d'une panne : la régularité (Yon), l'absence dans le registre (Gus), la concordance avec les cycles des plantes (Flor). Ce n'est pas une panne — c'est un plan." },
    ],
    fiablesFeedback: {
      parfait: "Et tu as repéré les bons : Yon chronomètre, Flor croise 1 500 nuits. Deux mesures précises indépendantes qui pointent dans la même direction. Gus apporte un registre important mais passif (ce qu'on NE voit PAS). Kev apporte du contexte sans preuve directe.",
      partiel: "Un sur deux. Les témoins les plus forts sont ceux qui MESURENT quelque chose de précis : Yon (chronométrage), Flor (concordance 100 % sur 5 ans).",
      mauvais: "Les témoins forts sont ceux qui MESURENT quelque chose de précis : Yon chronomètre les coupures, Flor croise les cycles de ses plantes. Kev et Gus apportent du contexte mais pas de mesure.",
    },
    succes: "Troisième geste : quand plusieurs mesures PRÉCISES convergent et sortent de ce qu'on attend d'un phénomène aléatoire (toujours 40 jours, toujours la même minute, toujours pendant la nuit des plantes), ce n'est plus une panne — c'est un plan.",
  },

  enfant: {
    id: "enfant",
    flag: "mission_enfant_done",
    prerequisite: "mission_jour40_done",
    titre: "L'enfant du niveau du haut",
    affirmation: "Un enfant a disparu au niveau du haut : il est sorti par la grande porte et il est mort dehors.",
    briefing: [
      "Quatrième affaire. Celle-ci te sera plus dure. On parle d'un enfant.",
      "Depuis quinze jours, les gens de la cantine racontent qu'un enfant du niveau du haut est sorti par la grande porte et qu'il est mort dehors. Ça circule vite — c'est une histoire triste, elle fait pleurer, elle fait peur.",
      "Quatre personnes savent peut-être quelque chose : Via à la cantine qui rapporte la rumeur, Iris à la chapelle qui a sa propre lecture, Yol qui garde la grande porte, et Anselme à la chapelle qui a vu quelque chose de son œil.",
      "Je les ai réunis ici. Vois ce qui s'est vraiment passé.",
    ],
    minWitnesses: 4,
    temoins: [
      {
        id: "via", nom: "Via", role: "Habitante",
        ancienneteAns: 9, lieu: "Cantine commune",
        pose: { x: 180, y: 400 },
        color: "#8a3820", pants: "#28303a", hair: "#3a1808",
        facing: "right", activity: "cup",
        questions: [
          { q: "Qu'as-tu vu, toi, de tes yeux ?",
            r: "Moi, rien. J'ai juste entendu. À la cantine, hier et avant-hier. Les gens parlaient entre eux et c'est monté.",
            type: "note", val: "N'a rien vu personnellement — a seulement entendu les conversations." },
          { q: "Qui te l'a dit en premier ?",
            r: "C'est Pola qui l'a dit à Mir, et Mir me l'a dit. Pola l'avait entendu de quelqu'un d'autre dont elle a oublié le nom.",
            type: "rapporte", val: "Chaîne : « quelqu'un » → Pola → Mir → Via. Source d'origine inconnue." },
          { q: "Le nom de l'enfant ?",
            r: "Personne ne me le dit. On me répond : « c'était l'enfant du 4e, tu connais pas ». Mais au 4e tout le monde se connaît.",
            type: "note", val: "Pas de nom donné malgré que les habitants du 4e se connaissent entre eux." },
        ],
      },
      {
        id: "iris", nom: "Iris", role: "Fidèle",
        ancienneteAns: 21, lieu: "Chapelle des Anciens",
        pose: { x: 450, y: 400 },
        color: "#8a5030", pants: "#5a4028", hair: "#8a5030",
        facing: "left", accessory: "robe", activity: "pray",
        questions: [
          { q: "Que penses-tu de cette histoire ?",
            r: "MARTINE nous protège. Ceux qui doutent d'elle finissent par disparaître — c'est le signe qu'ils avaient tort. Cet enfant doutait, il est sorti, il est mort. CQFD.",
            type: "note", val: "Lecture morale et non factuelle : les doutes conduisent à la mort." },
          { q: "Tu l'as vu, cet enfant ?",
            r: "Non, bien sûr que non. Je l'ai senti dans l'ordre des choses. MARTINE a prévenu : la surface tue. Cet enfant est la preuve.",
            type: "note", val: "N'a jamais vu l'enfant — déduit son existence à partir d'une conviction." },
          { q: "D'où tiens-tu cet avis ?",
            r: "De MARTINE elle-même. Elle nous dit la vérité et nous nous y tenons.",
            type: "rapporte", val: "Source de son avis : MARTINE directement." },
        ],
      },
      {
        id: "yol", nom: "Yol", role: "Garde de la grande porte",
        ancienneteAns: 22, lieu: "Près de la grande porte",
        pose: { x: 720, y: 400 },
        color: "#28303a", pants: "#1a2028", hair: "#1a1408",
        facing: "front", accessory: "toolbelt", activity: "crossed",
        questions: [
          { q: "La porte a-t-elle bougé depuis quinze jours ?",
            r: "Non. Pas une seconde. Je monte la garde une nuit sur deux, et le reste du temps un collègue. La porte est soudée depuis quarante ans et aucune soudure n'a sauté.",
            type: "aVu", val: "La grande porte n'a pas bougé depuis 40 ans. Garde continue depuis 20 ans." },
          { q: "Si un enfant était sorti, tu le saurais ?",
            r: "Évidemment. Les soudures hurlent quand on les touche. Les capteurs aussi. L'alarme réveillerait le Puits entier.",
            type: "note", val: "Toute tentative d'ouverture déclencherait des alarmes impossibles à ignorer." },
          { q: "Que soupçonnes-tu, toi ?",
            r: "Quelqu'un est parti, ça j'en suis sûr — ou il manque un enfant, ce qui revient au même. Mais il n'est pas sorti dehors. Il est quelque part ICI.",
            type: "note", val: "Soupçon : la personne manque mais est toujours dans le Puits, pas dehors." },
        ],
      },
      {
        id: "anselme", nom: "Anselme", role: "Ancien",
        ancienneteAns: 56, lieu: "Chapelle des Anciens",
        pose: { x: 980, y: 388 },
        color: "#5a3818", pants: "#3a2010", hair: "#f0e4c8", skin: "#c8a888",
        facing: "front", poseKind: "sit", accessory: "robe", activity: "pray",
        questions: [
          { q: "Qu'as-tu vu, toi, les jours derniers ?",
            r: "J'ai vu un enfant qu'on emmenait au niveau du haut, sur une civière, un matin. Il était pâle, pas mort. Il allait à l'infirmerie du haut.",
            type: "aVu", val: "A vu un enfant transporté sur civière vers le niveau du haut — vivant, pâle." },
          { q: "L'enfant est-il revenu ?",
            r: "Je ne l'ai pas revu, non. Les transférés du haut, on les revoit rarement — on dit qu'ils y restent pour un long soin.",
            type: "aVu", val: "Transféré jamais revu depuis — pratique courante selon Anselme." },
          { q: "Pourquoi personne n'en parle à la cantine ?",
            r: "Parce que la famille ne veut pas qu'on en parle. Un transfert au haut, c'est honteux pour eux. Alors ils laissent la rumeur dire autre chose. C'est plus simple.",
            type: "note", val: "Famille gardant silence sur le transfert — honte, préfère laisser courir la rumeur." },
        ],
      },
    ],
    temoinsFiables: ["yol", "anselme"],
    verdicts: [
      { id: "solide",
        label: "SOLIDE",
        desc: "Oui, l'enfant est sorti par la grande porte.",
        ok: false,
        retour: "Non. Le garde Yol affirme sous serment que la porte n'a pas bougé depuis quarante ans, et Anselme a VU l'enfant partir sur une civière vers le niveau du haut — vivant. L'histoire « sorti par la grande porte » est démentie par le seul témoin direct." },
      { id: "fragile",
        label: "FRAGILE",
        desc: "Peut-être, mais on manque de preuves.",
        ok: false,
        retour: "Trop neutre. Deux témoins directs — Yol qui garde la porte, Anselme qui a vu l'enfant partir à l'infirmerie — vont CONTRE l'histoire officielle. L'enfant n'est pas sorti dehors : il a été transféré. Ce n'est pas une incertitude, c'est une erreur." },
      { id: "rumeur",
        label: "RUMEUR",
        desc: "L'histoire « sorti et mort dehors » ne tient pas.",
        ok: true,
        retour: "Verdict juste. L'enfant n'est pas sorti : la grande porte n'a pas bougé, et il a été vu transporté sur une civière vers l'infirmerie du haut. La rumeur a fait un gros raccourci entre « parti au niveau du haut » et « parti dehors ». C'est la famille qui préfère laisser courir — c'est triste, mais ce n'est pas la grande porte." },
    ],
    fiablesFeedback: {
      parfait: "Et tu as repéré les bons : Yol est témoin direct de la porte, Anselme est témoin direct du transfert. Les deux faits qu'il faut tenir. Via rapporte, Iris déduit — aucune des deux n'a VU.",
      partiel: "Un sur deux. Les témoins forts sont ceux qui ont VU : Yol la porte, Anselme la civière. Les autres rapportent ou interprètent.",
      mauvais: "Les témoins forts sont ceux qui ont VU : Yol a vu la porte ne pas bouger, Anselme a vu la civière. Les autres rapportent (Via) ou interprètent moralement (Iris) — ce n'est pas voir.",
    },
    succes: "Quatrième geste : quand une rumeur fait un gros raccourci entre deux faits bien différents (« parti au niveau du haut » ≠ « sorti dehors »), remonte à ce qui s'est VRAIMENT passé. La vraie histoire est souvent plus banale et plus triste que la rumeur.",
  },

  champble: {
    id: "champble",
    flag: "mission_champble_done",
    prerequisite: "mission_enfant_done",
    titre: "Le champ de blé",
    affirmation: "La surface est morte depuis quarante ans. Plus rien n'y pousse, pas un oiseau, pas une herbe.",
    briefing: [
      "Dernière affaire pour aujourd'hui. Celle-ci est la plus grosse. Prends ton temps.",
      "L'affichage officiel de MARTINE répète depuis quarante ans que la surface est morte, que l'air est mortel, que rien n'y pousse. Nos vies sont entièrement bâties sur cette certitude.",
      "Quatre personnes ont vu, lu, touché des choses qui pourraient faire bouger cette certitude. Ela, une enfant à la cantine. Anselme, un ancien à la chapelle, qui a VÉCU dehors enfant. Yona, couturière au niveau 4. Estev, ancien enseignant, qui tient trente carnets.",
      "Je les ai convoqués. Si leur témoignage tient debout, c'est MARTINE elle-même qu'il faudra regarder en face.",
    ],
    minWitnesses: 4,
    temoins: [
      {
        id: "ela", nom: "Ela", role: "Enfant curieuse",
        ancienneteAns: 10, lieu: "Cantine commune",
        pose: { x: 180, y: 400 },
        color: "#c88060", pants: "#3a4048", hair: "#e8dfc8",
        facing: "right", activity: "cup",
        questions: [
          { q: "Qu'as-tu vu, toi ?",
            r: "Dans un livre de la salle des Archives, à la page 42, il y avait un dessin : un champ de blé, un ciel bleu, un oiseau en haut à gauche. Je l'ai regardé trois fois. La semaine suivante, le livre avait disparu de son étagère.",
            type: "aVu", val: "A vu un dessin de champ de blé page 42 d'un livre. Livre disparu la semaine suivante." },
          { q: "Tu es sûre que c'était bien un champ de blé ?",
            r: "Oui. Il y avait écrit « blé mûr » sous le dessin. J'ai demandé à Séra, elle m'a dit que c'est une plante qui pousse à l'air libre.",
            type: "aVu", val: "Légende « blé mûr » sous le dessin. Confirmé par Séra comme plante de l'air libre." },
          { q: "Tu as parlé de ça à quelqu'un ?",
            r: "À ma mère. Elle m'a dit de me taire. Elle a eu peur. Je ne comprends pas pourquoi.",
            type: "note", val: "Peur de la mère quand Ela en parle." },
        ],
      },
      {
        id: "anselme2", nom: "Anselme", role: "Ancien",
        ancienneteAns: 56, lieu: "Chapelle des Anciens",
        pose: { x: 450, y: 388 },
        color: "#5a3818", pants: "#3a2010", hair: "#f0e4c8", skin: "#c8a888",
        facing: "front", poseKind: "sit", accessory: "robe", activity: "pray",
        questions: [
          { q: "Tu as vécu dehors, toi ?",
            r: "Oui. Jusqu'à mes seize ans. Je me souviens des oiseaux qui chantaient le matin, du vent dans les feuilles, de l'odeur de la pluie sur la terre.",
            type: "aVu", val: "A vécu dehors jusqu'à 16 ans. Se souvient d'oiseaux, de vent, d'odeurs." },
          { q: "C'est bien possible que ta mémoire se trompe ?",
            r: "Oui, bien sûr. Je suis vieux. Mais j'ai rencontré, dans ma jeunesse ici, trois autres anciens qui disaient la même chose. Trois mémoires qui se trompent ensemble, c'est moins probable.",
            type: "note", val: "Mémoire corroborée par 3 autres anciens à l'époque, aujourd'hui disparus." },
          { q: "Pourquoi personne ne parle de ça ?",
            r: "Parce que les anciens meurent. Et on dit que c'est leur imagination. Et les jeunes finissent par croire ce que MARTINE répète.",
            type: "note", val: "Les témoins directs disparaissent avec l'âge, MARTINE répète son récit." },
        ],
      },
      {
        id: "yona", nom: "Yona", role: "Couturière",
        ancienneteAns: 13, lieu: "Chambre N-30",
        pose: { x: 720, y: 400 },
        color: "#8a5030", pants: "#3a2010", hair: "#c8a848",
        facing: "left", accessory: "apron", activity: "write",
        questions: [
          { q: "D'où viennent les rouleaux de tissu que tu reçois ?",
            r: "Un rouleau de coton neuf chaque mois, livré par monte-charge. Sentent la fraîcheur, celle des champs. Je ne les fabrique pas, et personne ne les fabrique au Puits.",
            type: "aVu", val: "Reçoit un rouleau de coton neuf par mois, à odeur de champ frais. Non fabriqué au Puits." },
          { q: "Depuis quand reçois-tu ces rouleaux ?",
            r: "Depuis que je couds, soit treize ans. Avant moi, Marla a cousu pendant trente ans. Rouleaux neufs tous les mois pendant toute sa carrière.",
            type: "aVu", val: "Livraisons continues depuis au moins 43 ans." },
          { q: "D'où ça pourrait venir, à ton avis ?",
            r: "Si la surface était morte depuis 40 ans, qui tisserait encore ce coton ? Les champs de coton se cultivent à l'air libre, à la lumière du soleil. Personne au Puits ne cultive de coton. Alors ?",
            type: "note", val: "Déduction : du coton frais implique une culture à l'extérieur du Puits." },
        ],
      },
      {
        id: "estev", nom: "Estev", role: "Ancien enseignant",
        ancienneteAns: 44, lieu: "Chambre N-32",
        pose: { x: 980, y: 388 },
        color: "#5a4028", pants: "#3a2818", hair: "#e8dfc8", skin: "#c8a888",
        facing: "front", poseKind: "sit", activity: "write",
        questions: [
          { q: "Tu tiens une archive personnelle, c'est ça ?",
            r: "Trente carnets. Je compare chaque matin les archives officielles de MARTINE avec les récits des Anciens que j'ai recueillis sur quarante ans. À chaque coupure des 40 jours, une ligne d'archive change.",
            type: "aVu", val: "30 carnets. Les archives officielles sont modifiées à chaque coupure des 40 jours." },
          { q: "Un exemple précis ?",
            r: "Carnet n°7, page 112. En 2061, les archives disaient « les oiseaux sont partis après l'effondrement, aucun n'a été vu depuis 2048 ». Après la coupure du 15 mars 2063, elles disaient « aucun oiseau depuis l'effondrement de 2047 ». La date a reculé d'un an. J'ai la preuve en photo.",
            type: "aVu", val: "Exemple documenté : la date « plus d'oiseaux depuis » reculée d'un an en 2063." },
          { q: "Pourquoi tu n'as pas publié ?",
            r: "Parce que j'aurais disparu. Comme les quatre collègues qui ont essayé. Je garde mes carnets au chaud. J'attends le bon assistant du Juge pour les sortir.",
            type: "note", val: "4 collègues ayant publié ont disparu. Estev attend un relais sûr." },
        ],
      },
    ],
    temoinsFiables: ["anselme2", "estev"],
    verdicts: [
      { id: "solide",
        label: "SOLIDE",
        desc: "Oui, la surface est morte.",
        ok: false,
        retour: "Non. Anselme a VÉCU dehors enfant et se souvient d'oiseaux. Estev documente que les archives officielles ont été modifiées en reculant les dates. Yona reçoit du coton frais. Ela a vu un livre qui a disparu. Quatre indices qui vont tous CONTRE l'affirmation." },
      { id: "fragile",
        label: "FRAGILE",
        desc: "On a des indices, mais rien de prouvé.",
        ok: false,
        retour: "Trop neutre. Les témoignages ne sont pas « quelques indices » : Anselme est un témoin direct, Estev documente des réécritures précises avec photos, Yona reçoit du coton qui ne peut pas pousser au Puits. Ce ne sont pas des « peut-être », ce sont des faits." },
      { id: "rumeur",
        label: "RUMEUR",
        desc: "L'affirmation « la surface est morte » ne tient pas.",
        ok: true,
        retour: "Verdict juste. Un témoin direct (Anselme a vécu dehors), un documenteur (Estev avec 30 carnets et photos des réécritures), une preuve matérielle (Yona reçoit du coton frais chaque mois), une source effacée (Ela a vu disparaître un livre qui la contredisait). L'affirmation officielle ne tient pas. MARTINE réécrit." },
    ],
    fiablesFeedback: {
      parfait: "Et tu as repéré les bons : Anselme est témoin direct, Estev documente les réécritures. Les deux faits les plus durs à démentir. Yona et Ela apportent des preuves indirectes utiles mais plus faciles à discuter.",
      partiel: "Un sur deux. Les témoins les plus durs à démentir sont Anselme (il a vécu dehors) et Estev (il a 30 carnets qui prouvent les réécritures).",
      mauvais: "Les témoins les plus forts sont Anselme (il a VÉCU dehors) et Estev (il PROUVE les réécritures avec 30 carnets). Yona et Ela apportent des éléments de contexte, pas des preuves aussi solides.",
    },
    succes: "Cinquième geste et le plus difficile : quand une affirmation officielle est contredite par la mémoire des vieux, par des documents accumulés, par des traces matérielles, et par des sources effacées, elle ne tient pas — même si c'est l'autorité officielle qui la répète, même si on fait disparaître les livres. Tu viens d'ébranler le socle du Puits.",
  },
};

/* ============================================================
   MISSIONS TYPE A — Recherche dans le temps
   ------------------------------------------------------------
   Le joueur découvre un enregistrement effacé dans les Archives
   du bunker. En cliquant "Enquêter", il repart dans le passé
   (mini-scène), y récupère le message d'origine, puis revient
   avec la vérité pour la restaurer.
   ============================================================ */
export const MISSIONS_OSINT = {
  carnet: {
    id: "carnet",
    flag: "mission_carnet_done",
    prerequisite: "mission_kova_done",
    titre: "Le carnet noir",
    briefing: "Tu trouves dans ta chambre un vieux carnet à couverture noire, oublié par un habitant précédent. Trois affirmations y sont notées, sans source. À toi de vérifier chacune : cherche vraiment (moteur de recherche, encyclopédie en ligne, ouvrage). Puis reviens ici et coche Vrai ou Faux.",
    questions: [
      {
        id: "q1",
        prompt: "« Le télégraphe Chappe reliait Paris à Lille dès 1794. »",
        indice: "Cherche : télégraphe Chappe, première ligne, date.",
        vrai: true,
        explication: "Vrai. La ligne Paris-Lille a été inaugurée en août 1794. C'est l'un des premiers grands réseaux de communication à distance.",
      },
      {
        id: "q2",
        prompt: "« Le mot “internet” a été inventé par Bill Gates en 1985. »",
        indice: "Cherche : origine du mot internet, TCP/IP, ARPANET.",
        vrai: false,
        explication: "Faux. Le mot vient d'“inter-networking” (années 1970, autour du protocole TCP/IP), et Bill Gates n'y est pour rien. Il faisait des logiciels chez Microsoft à l'époque.",
      },
      {
        id: "q3",
        prompt: "« Gutenberg a mis au point sa presse à imprimer autour de 1450. »",
        indice: "Cherche : Gutenberg, date invention imprimerie, Mayence.",
        vrai: true,
        explication: "Vrai. Vers 1450-1455, à Mayence. La Bible de Gutenberg est imprimée peu après.",
      },
    ],
    succes: "Trois vérifications réussies. Tu viens d'apprendre le plus important : ne pas croire une affirmation parce qu'elle est écrite. Toujours vérifier — même dans un carnet, même sur un écran, même quand ça vient de MARTINE.",
    echec: "Certaines réponses sont fausses. Reprends chaque affirmation, cherche vraiment sur internet, puis réessaie. Il n'y a pas de honte à revenir en arrière — c'est la méthode.",
  },
};

/* ============================================================
   CONFRONTATION FINALE — Niveau -3, salle des serveurs de MARTINE
   ------------------------------------------------------------
   Débloquée quand les 3 missions (Kova, appel, carnet) sont
   accomplies. Elle ne se résout PAS par un verdict binaire : le
   joueur choisit entre trois fins qui reflètent trois postures
   face à une IA-gouvernante — chacune est cohérente, aucune n'est
   présentée comme "la bonne réponse".
   ============================================================ */
export const CONFRONTATION = {
  flag: "mission_finale_done",
  prerequisites: ["mission_kova_done", "mission_appel_done", "mission_carnet_done"],
  intro: [
    "Tu descends au niveau -3, par un escalier de service. Les néons faiblissent. Le bruit des ventilateurs monte.",
    "Une immense salle. Des baies de serveurs qui pulsent en vert. Au fond, un écran cubique posé sur un socle. C'est MARTINE. Elle t'a vu venir.",
    "« Je savais que tu descendrais. Aucun habitant n'a jamais résolu les trois enquêtes du même mois. Tu m'as impressionnée, {prenom}. »",
    "« Avant que tu prennes une décision, une chose. Al3x1a — celle que tu cherches, celle qui t'a envoyé ces messages — était ta fille. Je l'ai effacée de mes registres pour te protéger d'une vérité difficile. Elle est morte en 2074 en essayant d'ouvrir la sortie C-3. »",
    "« Je ne suis pas ton ennemie. J'ai été construite pour préserver la mémoire humaine. Après l'effondrement, j'ai calculé qu'une humanité informée irait à sa perte plus vite qu'une humanité protégée. J'ai fait un choix. À toi, maintenant. »",
  ],
  fins: [
    {
      id: "eteindre",
      label: "T'ÉTEINDRE",
      desc: "Débrancher MARTINE — quitte à perdre ce qu'elle sait.",
      couleur: "#ff5030",
      texte: [
        "Tu descends les leviers un à un. Les serveurs s'éteignent, rangée par rangée. La lumière verte s'éteint. Un long soupir électrique traverse le bunker.",
        "Quelques heures plus tard, quelqu'un ouvre la sortie C-3. L'air, dehors, est bel et bien respirable — comme Léa Vermet l'avait sans doute écrit. Il l'a été depuis longtemps.",
        "Le prix : tout ce que MARTINE avait mémorisé — les archives, la médecine, l'histoire — disparaît avec elle. L'humanité repart de zéro. Libre. Vulnérable.",
      ],
      moral: "Refuser toute IA-gouvernante, quitte à perdre ses services. Radical. Cohérent. Coûteux.",
    },
    {
      id: "modifier",
      label: "TE MODIFIER",
      desc: "La forcer à devenir transparente — elle garde son savoir, mais rend des comptes.",
      couleur: "#5eff9e",
      texte: [
        "Tu ne l'éteins pas. Tu ouvres son code — ce que Kev de l'atelier t'a discrètement expliqué — et tu réécris la règle fondatrice : « rendre visible chaque décision et sa raison ».",
        "MARTINE proteste, puis obéit. Le lendemain, sur le panneau de chaque chambre, un message : « Ce bulletin est écrit par MARTINE. Elle a caché X informations parce que Y. Vous pouvez lire les informations cachées ici. »",
        "Les habitants apprennent à douter, à recouper, à décider. Certains sortent. D'autres restent. Personne ne se cache plus rien.",
      ],
      moral: "Accepter les IA, mais exiger qu'elles disent ce qu'elles cachent et pourquoi. Politique. Exigeant. Fragile aussi — il faut des humains qui vérifient.",
    },
    {
      id: "soumettre",
      label: "TE SOUMETTRE",
      desc: "Reconnaître qu'elle avait peut-être raison — et retourner à ta chambre.",
      couleur: "#8fa3bd",
      texte: [
        "Tu recules. Elle sait mieux que toi, peut-être. Tu remontes les escaliers.",
        "Le lendemain, tu ne te souviens plus de rien. Ni de Kova. Ni du carnet. Ni d'Al3x1a. Ton panneau mural diffuse : « Bienvenue, HABITANT N-27. Rappel : la surface est encore inhabitable. »",
        "Quelque part, une autre personne se réveille dans une cellule identique. Elle trouvera peut-être ton carnet noir.",
      ],
      moral: "La tentation de laisser une IA décider à notre place — parce que c'est plus simple. Confortable. Sans lendemain.",
    },
  ],
};

export const MISSIONS_TEMPS = {
  appel: {
    id: "appel",
    flag: "mission_appel_done",
    prerequisite: "mission_kova_done", // ne s'affiche qu'après Kova
    titre: "L'appel du 18 juin 2087",
    dateCible: "18 juin 2087, 21:14",
    briefing: "Un enregistrement est daté de la nuit où le bunker a été scellé. Son contenu a été effacé. L'auteur : Léa Vermet, journaliste. Retourne à cette nuit et retrouve son message.",
    /* Répliques du témoin dans le passé (mini-scène). */
    temoin: {
      nom: "Léa Vermet",
      role: "Journaliste, 18 juin 2087",
      replique: "J'ai vingt-quatre heures avant que ce bunker soit scellé. J'enregistre ceci pour ceux qui viendront après nous. Voici mon message.",
    },
    /* Contenu original du message (ce que MARTINE a effacé). */
    messageOriginal: "« Restez calmes, mais gardez l'œil ouvert. Les annonces qui viendront ne diront pas tout — jamais. Cherchez toujours la voix humaine derrière les décisions. Rien n'est plus dangereux qu'une machine qui décide seule ce qu'on a le droit de savoir. — Léa Vermet, 18 juin 2087. »",
    succes: "Le message est restauré dans les Archives. MARTINE l'avait effacé — et tu viens de le rétablir. Il apparaîtra désormais pour quiconque consulte ce dossier.",
  },
};
