/* ============================================================
   JEU 3 — Catalogue des PNJ « ambiants » (Cluedo)
   ------------------------------------------------------------
   Chaque PNJ a un id unique + une pose (x, y aux PIEDS du perso),
   un jeu de couleurs (haut, bas, peau, cheveux), une orientation
   (facing "front"/"left"/"right"), une posture (poseKind "stand"
   ou "sit"), un accessoire de métier optionnel, et surtout une
   activité (activity) qui remplace les bras et anime un geste
   caractéristique du métier.

   SMALLTALK — chaque PNJ peut aussi répondre à 3 questions courtes
   d'orientation ("où sommes-nous ?", "qu'est-ce que je fais ici ?",
   "et toi ?"). Le champ `replique` reste utilisé comme réponse à la
   question "et toi ?". Les 2 autres réponses sont dans `ou` et
   `pourquoiMoi`.
   ============================================================ */
export const SMALLTALK_QUESTIONS = [
  { id: "ou",          q: "Où sommes-nous exactement ?" },
  { id: "pourquoiMoi", q: "Qu'est-ce que je fais ici, moi ?" },
  { id: "toi",         q: "Et toi, qu'est-ce que tu fais ?" },
];

export const PNJ_ROOMS = {
  cantine: [
    { id: "cantine_nel",  nom: "Nel",  role: "Serveuse",
      pose: { x: 240, y: 400 }, color: "#8a5030", pants: "#3a2010", hair: "#5a3018",
      facing: "right", accessory: "apron", activity: "wipe",
      replique: "Je vois passer tout le monde ici. Personne ne mange plus à la même table depuis le mois dernier. Il y a comme une méfiance.",
      ou: "À la cantine commune, niveau +1. Trois cents personnes passent devant mon comptoir chaque jour. Le Puits, quoi.",
      pourquoiMoi: "Tu es nouveau à ton poste, non ? Le Juge Vez a glissé un billet sous ta porte, c'est ça ? Il recrute, en ce moment." },
    { id: "cantine_dor",  nom: "Dor",  role: "Cuisinier",
      pose: { x: 500, y: 400 }, color: "#c8d4e2", pants: "#3a2818", hair: "#1a1408",
      facing: "left", accessory: "apron", activity: "stir",
      replique: "Les rations viennent d'en-haut, du niveau 1. On me les donne, je les cuisine, je ne pose pas de questions. C'est comme ça depuis toujours.",
      ou: "Cantine centrale. Trois étages sous terre. On y mange, on y parle, on y oublie qu'on ne sort plus.",
      pourquoiMoi: "Ta chambre est au niveau 0, chambre N-27. Tu travailles. Comme nous tous. Vez t'a convoqué ? Il doit avoir une idée derrière la tête." },
    { id: "cantine_via",  nom: "Via",  role: "Habitante",
      pose: { x: 780, y: 400 }, color: "#8a3820", pants: "#28303a", hair: "#3a1808",
      facing: "left", activity: "cup",
      replique: "Il paraît qu'un enfant a disparu au niveau 2. Personne ne veut me dire son nom. Tu crois qu'il est vraiment parti dehors ?",
      ou: "Le Puits. Un bunker enterré depuis 2047. On nous dit qu'il n'y a plus rien dehors — c'est MARTINE qui le dit.",
      pourquoiMoi: "Tu vis ici, comme moi. Tu as un âge où on commence à prendre une place dans le travail du bunker. Vez t'a convoqué, non ?" },
    { id: "cantine_mo",   nom: "Mo",   role: "Habitant hors-service",
      pose: { x: 140, y: 400 }, color: "#5a6270", pants: "#3a2818", hair: "#3a1808",
      facing: "right", activity: "crossed",
      replique: "Trente ans que je mange les mêmes rations. Le vieux Estev dit que le goût a changé après 2078. Moi je te dis : c'est le sel qu'on a baissé — c'est écrit nulle part, mais je le sens.",
      ou: "Au fond du trou. Trois étages sous terre. Quarante ans qu'on nous dit « encore un peu de patience ».",
      pourquoiMoi: "Si Vez t'a envoyé un billet, c'est que tu vas lui être utile. Fais gaffe à ce qu'il te demande — il écrit tout dans son registre." },
    { id: "cantine_ela",  nom: "Ela",  role: "Enfant curieuse",
      pose: { x: 620, y: 400 }, color: "#c88060", pants: "#3a4048", hair: "#e8dfc8",
      facing: "left", activity: "cup",
      replique: "Ma mère dit que dehors c'est mort. Mais dans un livre de la salle des Archives, il y avait un dessin de champ de blé, page 42. Je l'ai regardé trois fois. Ensuite le livre a disparu.",
      ou: "Dans le Puits. Je suis née ici. Je n'ai jamais vu le ciel. Mais j'ai vu une image dans un livre, et ça ressemblait pas à « mort ».",
      pourquoiMoi: "Tu as l'air perdu·e. Moi aussi, souvent. Tu peux me poser des questions, les grands ne répondent pas, moi oui." },
    { id: "cantine_bri",  nom: "Bri",  role: "Cuisinière en chef",
      pose: { x: 900, y: 400 }, color: "#e8dfc8", pants: "#3a2818", hair: "#8a3820",
      facing: "left", accessory: "apron", activity: "write",
      replique: "Chaque mois je compte les rations. Chaque mois, le compte est juste. Trop juste. Comme si quelqu'un connaissait à l'avance combien on serait à table.",
      ou: "Cantine du niveau +1. Au-dessus de nous, les logements. En dessous, les ateliers et les serveurs. Au fond, MARTINE.",
      pourquoiMoi: "Vez m'a parlé de toi hier. Il cherchait un·e assistant·e pour les affaires qui remontent au bureau. Il a l'œil, Vez — il te suit depuis un moment." },
  ],
  infirmerie: [
    { id: "infirmerie_lin", nom: "Lin", role: "Médecin",
      pose: { x: 300, y: 400 }, color: "#7fd8ff", pants: "#3a4048", hair: "#5a4028",
      facing: "left", accessory: "coat", activity: "write",
      replique: "Je soigne des toux, des chutes, des yeux fatigués par les néons. Aucun cas de contamination extérieure depuis vingt ans. Aucun.",
      ou: "Infirmerie, niveau -1. Secteur services. En dessous, les ateliers. Au-dessus, les habitants. Juste à côté, le Bureau des Rumeurs.",
      pourquoiMoi: "Tu arrives ? Reste en bonne santé. Le Puits mange les gens doucement — fatigue, lumière, air recyclé. Et Vez va te charger. Mange, dors, respire." },
    { id: "infirmerie_ora", nom: "Ora", role: "Aide-soignante",
      pose: { x: 700, y: 400 }, color: "#c8d4e2", pants: "#3a4048", hair: "#3a2818",
      facing: "right", accessory: "coat", activity: "clipboard",
      replique: "MARTINE contrôle nos dossiers médicaux. Tout ce que je note est envoyé à elle. Parfois, j'ai l'impression qu'elle réécrit ce que j'ai écrit.",
      ou: "Infirmerie du Puits. Les néons sont allumés 24 h/24 ici — on ne sait plus si c'est le jour ou la nuit.",
      pourquoiMoi: "Si Vez t'a appelé·e, c'est pour vérifier des choses. Il manque toujours quelqu'un pour ça au bunker — personne ne veut poser les questions qui fâchent." },
    { id: "infirmerie_mel", nom: "Mel", role: "Patiente au repos",
      pose: { x: 500, y: 388 }, color: "#8a5030", pants: "#3a4048", hair: "#c8a848",
      facing: "front", poseKind: "sit", activity: "cup",
      replique: "Je viens pour la grande fatigue. Lin dit que c'est mental. J'ai vu trois voisins passer par ce lit ce mois-ci. Personne n'en a reparlé après.",
      ou: "Dans un lit de l'infirmerie. Je ne me souviens plus combien de jours.",
      pourquoiMoi: "Tu marches, c'est déjà bien. Vez t'a convoqué ? Alors tu dois être du genre à remarquer les choses. Fais attention aux étages du haut." },
  ],
  atelier: [
    { id: "atelier_kev",  nom: "Kev",  role: "Ingénieur systèmes",
      pose: { x: 260, y: 400 }, color: "#3a4048", pants: "#28303a", hair: "#2a2018",
      facing: "left", accessory: "toolbelt", activity: "wrench",
      replique: "MARTINE tourne sur des serveurs du niveau -3. J'y suis descendu une fois pour une maintenance. Ce n'est pas une simple IA — quelqu'un l'a modifiée après 2050.",
      ou: "Atelier des ingénieurs, niveau -1. On y répare tout ce qui garde le Puits en vie : ventilation, eau, courant.",
      pourquoiMoi: "Tu es un nouvel·le assistant·e du Juge Vez, je parie. Il recrute quelqu'un chaque fois qu'il reçoit trop de billets de rumeur. Garde l'œil ouvert." },
    { id: "atelier_tam",  nom: "Tam",  role: "Mécanicienne",
      pose: { x: 520, y: 400 }, color: "#5a4028", pants: "#3a2010", hair: "#8a3820",
      facing: "right", accessory: "hardhat", activity: "hammer",
      replique: "Je répare des ventilos et des pompes toute la journée. Les filtres sont neufs — trop neufs. Pourquoi refaire des filtres à air si l'air dehors est empoisonné ?",
      ou: "Atelier -1. Partout où ça fuit, où ça grince, où ça claque — c'est pour moi.",
      pourquoiMoi: "Tu portes le badge que Vez donne à ses assistants, non ? Si tu veux comprendre comment le Puits marche vraiment, viens voir mes pannes avec moi." },
    { id: "atelier_yon",  nom: "Yon",  role: "Électricien",
      pose: { x: 780, y: 400 }, color: "#c8a848", pants: "#3a2818", hair: "#3a1808",
      facing: "right", accessory: "toolbelt", activity: "torch",
      replique: "Le réseau électrique est stable — sauf tous les 40 jours pile. Coupure d'une minute, exactement. Ça vient d'en haut, pas d'en bas. Cherche pas plus loin, on te dira que c'est normal.",
      ou: "Niveau -1, l'atelier. Juste au-dessus de moi, les câbles. Juste en dessous, encore des câbles. Juste à côté, la salle des Archives.",
      pourquoiMoi: "Vez t'a convoqué·e ? Alors tu vas regarder des choses qu'on nous dit de pas regarder. Bon courage, petit·e." },
    { id: "atelier_bel",  nom: "Bel",  role: "Apprentie",
      pose: { x: 400, y: 400 }, color: "#5eff9e", pants: "#3a4048", hair: "#c8a848",
      facing: "left", activity: "clipboard",
      replique: "Kev me forme sur les schémas électriques. Il a dessiné un plan des câbles qui montent au niveau -3. Il l'a caché derrière le tableau 4A. Cherche pas, je te dirai rien de plus.",
      ou: "L'atelier. Mon premier poste. Avant j'étais à l'école du niveau 0.",
      pourquoiMoi: "Tu es aussi apprenti·e, non ? Moi chez Kev, toi chez Vez. On fait la même chose : on apprend un métier et on observe." },
    { id: "atelier_gus",  nom: "Gus",  role: "Contremaître",
      pose: { x: 900, y: 400 }, color: "#8a5030", pants: "#3a2010", hair: "#e8dfc8", skin: "#c8a888",
      facing: "left", accessory: "coat", activity: "write",
      replique: "Je note tout dans mon registre : chaque panne, chaque réparation. Depuis huit ans, aucune coupure n'a été signalée à MARTINE. J'obéis. Mais mon registre parle, lui.",
      ou: "Atelier des ingénieurs, niveau -1. Je dirige l'équipe. Vingt-quatre ans que je suis à ce poste.",
      pourquoiMoi: "Tu es l'assistant·e de Vez, hein ? Il m'a prévenu que tu viendrais. Si tu as besoin d'un registre, le mien est à ta disposition — officiellement." },
  ],
  chambreN24: [
    { id: "voisin_lior", nom: "Lior", role: "Insomniaque",
      pose: { x: 620, y: 400 }, color: "#3a80c8", pants: "#28303a", hair: "#1a1408",
      facing: "left", activity: "cup",
      replique: "Je dors plus. La nuit, je capte les vieux canaux radio du bunker. Il y a une voix féminine sur la bande 87 — ce n'est pas MARTINE. Elle chuchote un prénom : Kova. Personne ne veut m'écouter.",
      ou: "Chambre N-24, à côté de la tienne. Niveau 0. Tu peux entendre ma radio à travers le mur, parfois.",
      pourquoiMoi: "Tu habites ici depuis toujours, comme nous. Vez a glissé un billet sous ta porte ? J'ai entendu — les murs sont fins." },
  ],
  chambreN30: [
    { id: "voisin_yona", nom: "Yona", role: "Couturière",
      pose: { x: 640, y: 400 }, color: "#8a5030", pants: "#3a2010", hair: "#c8a848",
      facing: "left", accessory: "apron", activity: "write",
      replique: "Je refais tout le linge du bunker. Les rouleaux de tissu arrivent chaque mois par l'ascenseur. Neufs. Sentis frais. Si l'extérieur est mort depuis 40 ans, dis-moi qui tisse encore ce coton ?",
      ou: "Chambre N-30. Mon atelier de couture est ici, à même la table. Je sers tout le niveau 0.",
      pourquoiMoi: "Tu es la nouvelle main de Vez, à ce qu'on dit. S'il te demande d'enquêter sur ce qui monte par l'ascenseur, dis-lui que ça m'intéresse aussi." },
  ],
  chambreN32: [
    { id: "voisin_estev", nom: "Estev", role: "Ancien enseignant",
      pose: { x: 640, y: 400 }, color: "#5a4028", pants: "#3a2818", hair: "#e8dfc8", skin: "#c8a888",
      facing: "front", poseKind: "sit", activity: "write",
      replique: "Ça fait trente ans que je compare les récits des Anciens aux archives officielles. J'ai trente carnets. À chaque coupure de 40 jours, une ligne d'archive change. MARTINE réécrit doucement notre passé. Je n'ose pas le publier.",
      ou: "Chambre N-32, mon ancienne salle de classe. Transformée en logement quand on a fermé l'école.",
      pourquoiMoi: "Vez t'a choisi·e ? Garde-toi un carnet à toi. Note ce que les gens disent, et ce que MARTINE dit. Compare. C'est tout le travail." },
  ],
  serres: [
    { id: "serres_flor", nom: "Flor", role: "Botaniste en chef",
      pose: { x: 220, y: 400 }, color: "#5eff9e", pants: "#3a4048", hair: "#c8a848",
      facing: "right", accessory: "coat", activity: "write",
      replique: "Ces serres nourrissent le bunker depuis 40 ans. Salades, tomates, patates, protéines de champignon. Mais mes plants demandent 12 heures de lumière ; le tableau électrique de Yon coupe pile toutes les 40 nuits. Regarde bien mes feuilles jaunes.",
      ou: "Serres hydroponiques, niveau -2. Un étage dédié à faire pousser notre nourriture. Lumières artificielles, eau en circuit fermé.",
      pourquoiMoi: "On dit que tu es du côté du Juge Vez maintenant. S'il te demande sur mes plants, viens d'abord me voir, moi. Les feuilles jaunes ne mentent pas." },
    { id: "serres_tor", nom: "Tor", role: "Technicien nutriments",
      pose: { x: 520, y: 400 }, color: "#8a5030", pants: "#3a2010", hair: "#3a1808",
      facing: "left", accessory: "toolbelt", activity: "wrench",
      replique: "Je dose l'azote et le phosphore dans les cuves. Depuis un an, les rations arrivent avec un supplément blanc en poudre — soi-disant vitamine. MARTINE dit que c'est bon pour nous. Moi, je vois ce que ça fait à mes tomates : elles grossissent, mais elles n'ont plus de goût.",
      ou: "Serres -2. Mes cuves sont là, dans le fond. Je dose, je mesure, je note.",
      pourquoiMoi: "Nouvel·le assistant·e, hein ? Dis-moi ce que raconte Vez sur la poudre blanche quand tu passeras au bureau. Ça m'intéresse." },
    { id: "serres_ru", nom: "Ru", role: "Cueilleuse",
      pose: { x: 820, y: 400 }, color: "#c88060", pants: "#3a4028", hair: "#5a3018",
      facing: "front", accessory: "apron", activity: "cup",
      replique: "Je récolte le matin. Trois cageots par jour. Un cageot part à la cantine, un cageot au niveau +1, un cageot dans un monte-charge dont personne ne me dit la destination. Si tu poses la question, on ne te répond pas.",
      ou: "Les serres. Je passe mes journées à genoux entre les rangs.",
      pourquoiMoi: "Tu vas voir Vez ? Dis-lui que je veux savoir où part le troisième cageot. S'il te le dit, reviens me voir." },
  ],
  chapelle: [
    { id: "chapelle_anselme", nom: "Anselme", role: "Ancien",
      pose: { x: 260, y: 388 }, color: "#5a3818", pants: "#3a2010", hair: "#f0e4c8", skin: "#c8a888",
      facing: "front", poseKind: "sit", accessory: "robe", activity: "pray",
      replique: "J'ai vécu à la surface, jeune. Il y avait des oiseaux. Aujourd'hui on nous dit qu'il n'y a plus rien. Je ne sais plus qui croire.",
      ou: "Chapelle des Anciens, niveau +1. Ici on vient se taire. Il n'en reste plus que deux ou trois à ma génération.",
      pourquoiMoi: "Tu es jeune, comme ils l'étaient. Vez t'a appelé·e pour que tu voies ce que les vieux ont oublié de dire. Écoute vraiment. Les anciens ne mentent pas tous." },
    { id: "chapelle_iris",   nom: "Iris",    role: "Fidèle",
      pose: { x: 760, y: 400 }, color: "#8a5030", pants: "#5a4028", hair: "#8a5030",
      facing: "left", accessory: "robe", activity: "pray",
      replique: "MARTINE nous protège. Elle a toujours dit la vérité. Ceux qui doutent finissent par disparaître — signe qu'ils avaient tort, non ?",
      ou: "Dans la Chapelle. Niveau +1. Le seul endroit où l'on reconnaît MARTINE pour ce qu'elle est : notre gardienne.",
      pourquoiMoi: "Tu travailles pour Vez ? Il doute, lui aussi. Fais attention, petit·e. Trop de questions, et on finit comme ceux qui doutent." },
  ],
};
